name:                gravity-assist
version:             0.1.0.0
github:              "JacekDuszenko/gravity-assist"
license:             BSD3
author:              "Jacek Duszenko"
maintainer:          "jacek.duszenko@gmail.com"
copyright:           "2018 Jacek Duszenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            App category here

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JacekDuszenko/gravity-assist Jacek Duszenko JacekDuszenko/gravity-assist#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  gravity-assist-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gravity-assist

tests:
  gravity-assist-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gravity-assist
